[colors.primary]
background = "#110a19"
foreground = "#c3c1c5"

[colors.cursor]
text = "#110a19"
cursor = "#c3c1c5"

[colors.vi_mode_cursor]
text = "#110a19"
cursor = "#c3c1c5"

[colors.search.matches]
foreground = "#110a19"
background = "#c3c1c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#63596e"
background = "#928e98"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#110a19"
red = "#9f4e21"
green = "#764243"
yellow = "#99553f"
blue = "#b0632c"
magenta = "#ad6a47"
cyan = "#6f5168"
white = "#928e98"

[colors.bright]
black = "#63596e"
red = "#D5682D"
green = "#9E585A"
yellow = "#CC7255"
blue = "#EB843B"
magenta = "#E78E5F"
cyan = "#946D8B"
white = "#c3c1c5"

[colors.dim]
black = "#c3c1c5"
red = "#D5682D"
green = "#E78E5F"
yellow = "#CC7255"
blue = "#EB843B"
magenta = "#9E585A"
cyan = "#946D8B"
white = "#63596e"

