[colors]
background = '#110a198e'
black = '#110a19'
blue = '#9f4e21'
cursor = '#c3c1c5'
cyan = '#764243'
foreground = '#c3c1c5'
green = '#99553f'
magenta = '#b0632c'
red = '#ad6a47'
tabs = '#c3c1c5'
tabs-active = '#6f5168'
white = '#c3c1c5'
yellow = '#928e98'
dim-black = '#110a198e'
dim-blue = '#9f4e218e'
dim-cyan = '#7642438e'
dim-foreground = '#c3c1c58e'
dim-green = '#99553f8e'
dim-magenta = '#b0632c8e'
dim-red = '#ad6a478e'
dim-white = '#6f51688e'
dim-yellow = '#928e988e'
light-black = '#D5682D'
light-blue = '#9E585A'
light-cyan = '#CC7255'
light-foreground = '#EB843B'
light-green = '#E78E5F'
light-magenta = '#946D8B'
light-red = '#c3c1c5'
light-white = '#D5682D'
light-yellow = '#9E585A'
